# Generated by Django 4.1 on 2022-09-06 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('83f10b13-61a2-4391-924c-768a5d55eccc')),
        ),
    ]
