# Generated by Django 4.1 on 2022-09-06 01:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0002_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('30681c2d-b19c-4ce0-9ddd-8b1b86d80b57')),
        ),
    ]
