# Generated by Django 4.1 on 2022-09-06 02:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0004_alter_applicationtoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('0aae624d-db56-4243-9b0e-3f512dcabdbd')),
        ),
    ]
