# Generated by Django 4.1 on 2022-09-06 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0006_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('9b30846d-f511-4567-a9e4-08917d64d6c7')),
        ),
    ]
