# Generated by Django 4.1 on 2022-09-14 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0007_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('cadd499e-f479-4595-b7f5-5f0b06838c11')),
        ),
    ]
