# Generated by Django 4.1 on 2022-09-14 03:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0008_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('8ac74016-b500-4f37-bb9b-5ec458a94205')),
        ),
    ]
