# Generated by Django 4.1 on 2022-09-14 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0009_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('80eaa1b5-e46f-4a66-9289-62f43a268fb8')),
        ),
    ]
