# Generated by Django 4.1 on 2022-09-14 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0010_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('cca8f255-6b2a-47fb-9245-d0a9eccb76cd')),
        ),
    ]
