# Generated by Django 4.1 on 2022-09-14 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0011_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('fd14ae19-e79f-4d5a-b67d-b3784eb0653c')),
        ),
    ]
