# Generated by Django 4.1 on 2022-09-15 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0016_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('61b00a6a-da26-4a26-bf3e-d56531f5ff71')),
        ),
    ]
