# Generated by Django 4.1 on 2022-09-23 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0017_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('576411ac-61b0-46d4-a7bf-25913cdf4bdd')),
        ),
    ]
