# Generated by Django 4.1 on 2022-09-23 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0018_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('9d5e93cd-c15f-4e0e-b3c8-c216a6e08d2c')),
        ),
    ]
