# Generated by Django 4.1 on 2022-09-23 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apptoken', '0019_alter_applicationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtoken',
            name='token',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('a86634c8-20d8-4e73-9ef6-dc998ea2d96f')),
        ),
    ]
